pid:
  position:
    x:
      Kp: 0.85
      Ki: 0
      Kd: 0.40
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    y:
      Kp: 0.80
      Ki: 0
      Kd: 0.05
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    z:
      Kp: 1.43
      Ki: 0
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    roll:
      Kp: 0.05
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    pitch:
      Kp: 0.05
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: 0
        max: 0
      derivative_type: 1
      error_ramp_rate: 1000
    yaw:
      Kp: 0.09
      Ki: 0.003
      Kd: 0
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
  position_cascaded:
    x:
      Kp: 4
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    y:
      Kp: 3.5
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    z:
      Kp: 1
      Ki: 0
      Kd: 1.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    roll:
      Kp: 0.8
      Ki: 0
      Kd: 0.4
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    pitch:
      Kp: 0
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: 0
        max: 0
      derivative_type: 1
      error_ramp_rate: 1000
    yaw:
      Kp: 1
      Ki: 0
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
  velocity:
    x:
      Kp: 1.75
      Ki: 0.02
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    y:
      Kp: 1
      Ki: 0.02
      Kd: 0.05
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    z:
      Kp: 0.5
      Ki: 0.5
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    roll:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    pitch:
      Kp: 0
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: 0
        max: 0
      derivative_type: 0
      error_ramp_rate: 1000
    yaw:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
desired_power_limits:
  x:
    min: -1
    max: 1
  y:
    min: -1
    max: 1
  z:
    min: -1
    max: 1
  roll:
    min: -1
    max: 1
  pitch:
    min: -1
    max: 1
  yaw:
    min: -1
    max: 1
static_power_global:
  x: 0
  y: 0
  z: -0.206
power_scale_factor: 1
# all x positions assume the corner link is 10.41527MM +x than it actually is
thrusters:
  - name: middle_right_first
    type: T200
    pos: [-0.15501, -0.34805, -0.003175]
    rpy: [0, 90, 0]
  - name: middle_right_second
    type: T200
    pos: [-0.32582, -0.34805, -0.003175]
    rpy: [0, 90, 0]
  - name: front_right
    type: T200
    pos: [0.001895, -0.38866, -0.003175]
    rpy: [0, 0, -135]
  - name: back_right
    type: T200
    pos: [-0.48273, -0.38866, -0.003175]
    rpy: [0, 0, 135]
  - name: back_left
    type: T200
    pos: [-0.48273, 0.09596, -0.003175]
    rpy: [0, 0, -135]
  - name: middle_left_first
    type: T200
    pos: [-0.15501, 0.05535, -0.003175]
    rpy: [0, 90, 0]
  - name: middle_left_second
    type: T200
    pos: [-0.32582, 0.05535, -0.003175]
    rpy: [0, 90, 0]
  - name: front_left
    type: T200
    pos: [0.001895, 0.09596, -0.003175]
    rpy: [0, 0, 135]
wrench_matrix_file_path: data/crush_wrench.csv
wrench_matrix_pinv_file_path: data/crush_wrench_pinv.csv
