pid:
  position:
    x:
      Kp: 0.84999999999999998
      Ki: 0
      Kd: 0.40000000000000002
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    y:
      Kp: 0.80000000000000004
      Ki: 0
      Kd: 0.14999999999999999
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    z:
      Kp: 1.4299999999999999
      Ki: 0
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    roll:
      Kp: 0.050000000000000003
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    pitch:
      Kp: 0.050000000000000003
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: 0
        max: 0
      derivative_type: 1
      error_ramp_rate: 1000
    yaw:
      Kp: 0.089999999999999997
      Ki: 0.0030000000000000001
      Kd: 0
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
  position_cascaded:
    x:
      Kp: 4
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    y:
      Kp: 3.5
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    z:
      Kp: 1
      Ki: 0
      Kd: 1.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    roll:
      Kp: 0.8
      Ki: 0
      Kd: 0.4
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
    pitch:
      Kp: 0
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: 0
        max: 0
      derivative_type: 1
      error_ramp_rate: 1000
    yaw:
      Kp: 1
      Ki: 0
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 1
      error_ramp_rate: 1000
  velocity:
    x:
      Kp: 1.75
      Ki: 0.02
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    y:
      Kp: 1
      Ki: 0.02
      Kd: 0.050000000000000003
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    z:
      Kp: 0.5
      Ki: 0.5
      Kd: 0.5
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    roll:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
    pitch:
      Kp: 0
      Ki: 0
      Kd: 0
      Ff: 0
      control_effort:
        min: 0
        max: 0
      derivative_type: 0
      error_ramp_rate: 1000
    yaw:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort:
        min: -1
        max: 1
      derivative_type: 0
      error_ramp_rate: 1000
desired_power_limits:
  x:
    min: -1
    max: 1
  y:
    min: -1
    max: 1
  z:
    min: -1
    max: 1
  roll:
    min: -1
    max: 1
  pitch:
    min: -1
    max: 1
  yaw:
    min: -1
    max: 1
static_power_global:
  x: 0
  y: 0
  z: -0.20599999999999999
power_scale_factor: 1
thrusters:
  - name: middle_right
    type: T200
    pos: [-0.2404152701, -0.42425, -0.003175]
    rpy: [0, 90, 0]
  - name: front_right
    type: T200
    pos: [3.360246e-05, -0.3867988726, -0.003175]
    rpy: [0, 0, -135]
  - name: back_right
    type: T200
    pos: [-0.4808641427, -0.3867988726, -0.003175]
    rpy: [0, 0, 135]
  - name: back_left
    type: T200
    pos: [-0.4808641427, 0.09409887258, -0.003175]
    rpy: [0, 0, -135]
  - name: middle_left
    type: T200
    pos: [-0.2404152701, 0.13155, -0.003175]
    rpy: [0, 90, 0]
  - name: front_left
    type: T200
    pos: [3.360246e-05, 0.09409887258, -0.003175]
    rpy: [0, 0, 135]
wrench_matrix_file_path: data/crush_wrench.csv
wrench_matrix_pinv_file_path: data/crush_wrench_pinv.csv